#development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: feednews_development
#  pool: 5
#  username: root
#  password:
#  host: localhost

#test:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: feednews_test
#  pool: 5
#  username: root
#  password:
#  host: localhost

#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: feednews_production
#  pool: 5
#  username: root
#  password:
#  host: localhost

default: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: root

development:
  <<: *defaults
  database: feednews_development

test:
  <<: *defaults
  database: feednews_test

#production:
#  adapter: postgresql
#  encoding: utf8
#  pool: 5
#  database: dfu37f755h1d41
#  username: qaeshdcibafgyw
#  password: Q6PElB8pDxPIdrk_EgfxIgqnnG
#  host: ec2-54-243-184-143.compute-1.amazonaws.com
#  port: 5542